In [1]:
import torch
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from XBNet.training_utils import training,predict
from XBNet.models import XBNETClassifier
from XBNet.run import run_XBNET

import glob
from pandas.core.common import flatten
import random

# Split1

In [2]:
# set path split1
split = 'split1'
path = "../5-fold_new/DATA"
train_path = "{}/{}/train/train_{}.csv".format(path,split,split)
test_path =  "{}/test.csv".format(path)
valid_path = "{}/{}/val/val_{}.csv".format(path,split,split)

In [3]:
print(train_path)
print(test_path)
print(valid_path)

../5-fold_new/DATA/split1/train/train_split1.csv
../5-fold_new/DATA/test.csv
../5-fold_new/DATA/split1/val/val_split1.csv


In [4]:
train_data = pd.read_csv(train_path)
print(train_data.shape)
x_train = train_data[train_data.columns[2:]]
print(x_train.shape)
y_train = train_data[train_data.columns[1]]
le = LabelEncoder()
y_train = np.array(le.fit_transform(y_train))
print(le.classes_)

(364, 32)
(364, 30)
['B' 'M']


In [5]:
# Load the testing set
test_data = pd.read_csv(test_path)
print(test_data.shape)
x_test = test_data[test_data.columns[3:]]
print(x_test.shape)
y_test = test_data[test_data.columns[2]]
le = LabelEncoder()
y_test = np.array(le.fit_transform(y_test))
print(le.classes_)

(114, 33)
(114, 30)
['B' 'M']


In [6]:
# Load the validation set
val_data = pd.read_csv(valid_path)
print(val_data.shape)
x_val = val_data[val_data.columns[2:]]
print(x_val.shape)
y_val = val_data[val_data.columns[1]]
le = LabelEncoder()
y_val = np.array(le.fit_transform(y_val))
print(le.classes_)

(91, 32)
(91, 30)
['B' 'M']


In [7]:
x_train = x_train.to_numpy()
x_test = x_test.to_numpy()

In [9]:
print(f'The shape of Train data is {x_train.shape}')
print(f'The shape of Test data is {x_test.shape}')

The shape of Train data is (364, 30)
The shape of Test data is (114, 30)


In [10]:
from sklearn.tree import DecisionTreeClassifier
tree_clf = DecisionTreeClassifier(criterion='gini', max_depth=2)

In [12]:
tree_clf.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=2)

In [13]:
y_test_pred = tree_clf.predict(x_test)

In [22]:
y_test_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0])

In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(f'The accuracy of the model is: {accuracy_score(y_test,y_test_pred)*100:0.2f}')
print()
print('confusion matrix')
print(f'{confusion_matrix(y_test, y_test_pred)}')

The accuracy of the model is: 86.84

confusion matrix
[[44  2]
 [13 55]]


In [15]:
from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier(n_estimators=100, random_state=32)

In [16]:
rf_clf.fit(x_train, y_train)

RandomForestClassifier(random_state=32)

In [17]:
y_train_pred = rf_clf.predict(x_train)
y_test_pred = rf_clf.predict(x_test)

In [18]:
print(f'The accuracy of the model on the train data: {accuracy_score(y_train, y_train_pred)*100:0.2f}')
print(f'The accuracy of the model on the test data: {accuracy_score(y_test, y_test_pred)*100:0.2f}')
print()
print('confusion matrix')
print(f'{confusion_matrix(y_test, y_test_pred)}')

The accuracy of the model on the train data: 100.00
The accuracy of the model on the test data: 90.35

confusion matrix
[[45  1]
 [10 58]]


In [19]:
rf_clf = RandomForestClassifier(n_estimators=10, max_depth=5, random_state=32, n_jobs=-1)
rf_clf.fit(x_train, y_train)
y_train_pred = rf_clf.predict(x_train)
y_test_pred = rf_clf.predict(x_test)

In [20]:
print(f'The accuracy of the model on the train data: {accuracy_score(y_train, y_train_pred)*100:0.2f}')
print(f'The accuracy of the model on the test data: {accuracy_score(y_test, y_test_pred)*100:0.2f}')
print()
print('confusion matrix')
print(f'{confusion_matrix(y_test, y_test_pred)}')

The accuracy of the model on the train data: 99.73
The accuracy of the model on the test data: 90.35

confusion matrix
[[44  2]
 [ 9 59]]


In [24]:
# accuracy score

print(accuracy_score(y_train, y_train_pred))

dtc_acc = accuracy_score(y_test, y_test_pred)
print(dtc_acc)

0.9972527472527473
0.9035087719298246
